🎖️ Integration specs 🎖️
kambereBr/Publisher pull request #8
Opened 2023-11-07 22:00 UTC by kambereBr

## Project requirements

- ✅ No Linters error
- ✅ Used correct GitFlow.
- Made sure that the N+1 problem is solved when fetching all posts and their comments for a user.

Before

![n+1-before](https://github.com/kambereBr/Publisher/assets/29512462/2b99a3af-0f9b-4a57-975d-ea47e5dd9e6f)

After

![n+1-after](https://github.com/kambereBr/Publisher/assets/29512462/584d4ee1-8675-4542-98db-7a6bcda4a4a7)

- Used Capybara to write integration tests for each view in the project (`User index page`, `user show page`, `User post index page`, `Post show page`)

2023-11-07 23:06 UTC, MahmoudBakr23 requested changes
Hello TEAM😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Great job on solving the N+1 query problems
- Well done on writing the required tests for each page so far
- Descriptive PR and README
- Correct Linters

However, there is always room for improvement.

> I'd like to remind you that your long hours of work are appreciated. However, the code review process is for improving your code, not criticizing it. 😄

 ## Required Changes ♻️
_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

N/A

Cheers, and Happy coding!👏👨‍💻💻

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-07 23:06 UTC, MahmoudBakr23 commented on spec/views/user_show_spec.rb
> +    click_link('See all posts')
- [ ] In the user's show page testing file, please add the following test as per project requirements: "A test that redirects to the post's show page when you click on a user's post." 🙏

2023-11-08 11:29 UTC, kambereBr commented on spec/views/user_show_spec.rb
> +    click_link('See all posts')
Dear @MahmoudBakr23, thanks for your review 👏

2023-11-08 11:41 UTC, Reem-lab commented on spec/views/user_show_spec.rb
> +    click_link('See all posts')
Hello @kambereBr I have a question you updated the user show but I think you didn't add a test that redirects to the post's show page right? to show a specific post for a user?

2023-11-08 12:49 UTC, kambereBr commented
Dear @MahmoudBakr23, the issue fixed. Thanks

2023-11-08 12:55 UTC, hiromataba approved these changes
# Status: Approved :tada: :tada: :tada: 
Hi @kambereBr  and @M-Anwar-Hussaini  :wave: :wave: 

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif)  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-08 12:57 UTC, kambereBr commented
Dear @hiromataba, thanks for your review

2023-11-08 14:34 UTC, merged